version: "3.8"
services:
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
