services:
  client:
    image: ${DOCKER_USERNAME}/goddess-within-client:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - goddess-net
    container_name: goddess-within-client-prod

  api:
    image: ${DOCKER_USERNAME}/goddess-within-api:latest
    restart: always
    container_name: goddess-within-api-prod
    ports:
      - "5000:3000"
    networks:
      - goddess-net
    env_file:
      - .env

networks:
  goddess-net:
    driver: bridge
